[project]
name = "root-core"
version = "0.1.1"
description = ""
authors = [{ name = "Ghaziriyadh", email = "ghazriyadh2@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.poetry]
packages = [{ include = "root_core", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
